# This is a basic workflow to help you get started with Actions

name: tanoshi CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: '* * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Echo dot
        run: |
          echo -n "." >> README.md
          
      - name: Git Settings
        run: |
          git config --local user.email "kemo.hashibiroko@gmail.com"
          git config --local user.name "hashibiroko"
          
      - name: Commit files
        run: |
          git add .
          git commit -m "tanoshi"
          git push origin master
